name: build

on:
  push:
    tags:
      - v*
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.35.2

        # Optional: working directory, useful for monorepos
        # working-directory: somedir

        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0
        args: --config=.golangci.yml

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        only-new-issues: false

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Test
      run: make test

    - name: Build
      run: make

  generate:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Create release-artifacts
        uses: actions/checkout@master

      - name: Generate
        uses: skx/github-action-build@master
        with:
          builder: make
